export const navlinks = [
    {
        name: "Near Me",
        href: "/home",
    },
    {
        name: "Trips",
        href: "/account?tab=trips",
    },
    {
        name: "Saved",
        href: "/account?tab=saved",
    },
   
   
]



export const gameOptions = [
  "Moose",
  "Grizzly Bear",
  "Black Bear",
  "Caribou",
  "Mountain Goat",
  "Dall Sheep",
  "Stone Sheep",
  "Bighorn Sheep",
  "Whitetail Deer",
  "Elk",
  "Puma",
  "Bobcat",
  "Lynx",
  "Wolf",
  "Wolverine",
  "Sitka Deer",
  "Turkey",
  "Bison",
  "Wild Pigs",
  "Gators",
  "Fox",
  "Other Small Game",
];

export const statesData = {
  canada: [
    { name: "Alberta", rate: "5%" },
    { name: "British Columbia", rate: "12%" },
    { name: "Manitoba", rate: "12%" },
    { name: "New Brunswick", rate: "15%" },
    { name: "Newfoundland and Labrador", rate: "15%" },
    { name: "Northwest Territories", rate: "5%" },
    { name: "Nova Scotia", rate: "15%" },
    { name: "Nunavut", rate: "5%" },
    { name: "Ontario", rate: "13%" },
    { name: "Prince Edward Island", rate: "15%" },
    { name: "Quebec", rate: "14.975%" },
    { name: "Saskatchewan", rate: "11%" },
    { name: "Yukon", rate: "5%" },
  ],
  usa: [
    { name: "Alabama", rate: "9.25%" },
    { name: "Alaska", rate: "1.76%" },
    { name: "Arizona", rate: "8.40%" },
    { name: "Arkansas", rate: "9.51%" },
    { name: "California", rate: "8.82%" },
    { name: "Colorado", rate: "7.78%" },
    { name: "Connecticut", rate: "6.35%" },
    { name: "Delaware", rate: "0%" },
    { name: "Florida", rate: "7.05%" },
    { name: "Georgia", rate: "7.35%" },
    { name: "Hawaii", rate: "4.44%" },
    { name: "Idaho", rate: "6.02%" },
    { name: "Illinois", rate: "8.82%" },
    { name: "Indiana", rate: "7%" },
    { name: "Iowa", rate: "6.94%" },
    { name: "Kansas", rate: "8.70%" },
    { name: "Kentucky", rate: "6%" },
    { name: "Louisiana", rate: "9.55%" },
    { name: "Maine", rate: "5.50%" },
    { name: "Maryland", rate: "6%" },
    { name: "Massachusetts", rate: "6.25%" },
    { name: "Michigan", rate: "6%" },
    { name: "Minnesota", rate: "7.49%" },
    { name: "Mississippi", rate: "7.07%" },
    { name: "Missouri", rate: "8.29%" },
    { name: "Montana", rate: "0%" },
    { name: "Nebraska", rate: "6.94%" },
    { name: "Nevada", rate: "8.23%" },
    { name: "New Hampshire", rate: "0%" },
    { name: "New Jersey", rate: "6.60%" },
    { name: "New Mexico", rate: "7.83%" },
    { name: "New York", rate: "8.52%" },
    { name: "North Carolina", rate: "6.98%" },
    { name: "North Dakota", rate: "6.96%" },
    { name: "Ohio", rate: "7.24%" },
    { name: "Oklahoma", rate: "8.98%" },
    { name: "Oregon", rate: "0%" },
    { name: "Pennsylvania", rate: "6.34%" },
    { name: "Rhode Island", rate: "7%" },
    { name: "South Carolina", rate: "7.43%" },
    { name: "South Dakota", rate: "6.40%" },
    { name: "Tennessee", rate: "9.55%" },
    { name: "Texas", rate: "8.20%" },
    { name: "Utah", rate: "7.19%" },
    { name: "Vermont", rate: "6.24%" },
    { name: "Virginia", rate: "5.75%" },
    { name: "Washington", rate: "9.29%" },
    { name: "West Virginia", rate: "6.55%" },
    { name: "Wisconsin", rate: "5.43%" },
    { name: "Wyoming", rate: "5.36%" },
  ],
   mexico: [
    { name: "Aguascalientes", rate: "0%" },
    { name: "Baja California", rate: "0%" },
    { name: "Baja California Sur", rate: "0%" },
    { name: "Campeche", rate: "0%" },
    { name: "Chiapas", rate: "0%" },
    { name: "Chihuahua", rate: "0%" },
    { name: "Coahuila", rate: "0%" },
    { name: "Colima", rate: "0%" },
    { name: "Durango", rate: "0%" },
    { name: "Guanajuato", rate: "0%" },
    { name: "Guerrero", rate: "0%" },
    { name: "Hidalgo", rate: "0%" },
    { name: "Jalisco", rate: "0%" },
    { name: "Mexico City", rate: "0%" },
    { name: "Michoacan", rate: "0%" },
    { name: "Morelos", rate: "0%" },
    { name: "Nayarit", rate: "0%" },
    { name: "Nuevo Leon", rate: "0%" },
    { name: "Oaxaca", rate: "0%" },
    { name: "Puebla", rate: "0%" },
    { name: "Queretaro", rate: "0%" },
    { name: "Quintana Roo", rate: "0%" },
    { name: "San Luis Potosi", rate: "0%" },
    { name: "Sinaloa", rate: "0%" },
    { name: "Sonora", rate: "0%" },
    { name: "Tabasco", rate: "0%" },
    { name: "Tamaulipas", rate: "0%" },
    { name: "Tlaxcala", rate: "0%" },
    { name: "Veracruz", rate: "0%" },
    { name: "Yucatan", rate: "0%" },
    { name: "Zacatecas", rate: "0%" },
    { name: "Quintana Roo", rate: "0%" },
    { name: "San Luis Potosi", rate: "0%" },
    { name: "Sinaloa", rate: "0%" },
    { name: "Other", rate: "0%" },
  ],
};
